# Testing Imports

In [1]:
# import function

from src.src import *

In [2]:
# get data

df = get_data()
df

,NAME_CONTRACT_TYPE_Cash loans,NAME_CONTRACT_TYPE_Revolving loans,NAME_CONTRACT_TYPE_nan,CODE_GENDER_F,CODE_GENDER_M,CODE_GENDER_XNA,CODE_GENDER_nan,FLAG_OWN_CAR_N,FLAG_OWN_CAR_Y,FLAG_OWN_CAR_nan,...,num_closed_bureau_credits,avg_ratio_bureau_cr_debt,ttl_bureau_cc_limit,cc_avg_credit_usage_ratio,avg_cc_cnt_ATM_drawings,prev_avg_ratio_credit_approved,prev_status_approved,prev_status_refused,prev_yield_high,prev_yield_low_action
0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,4.0,0.282517,0.000,NaN,NaN,0.957782,1.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,6.0,0.109236,31988.565,NaN,NaN,1.000000,1.0,0.0,0.0,0.0
2,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,3.0,0.000000,810000.000,NaN,NaN,1.057664,3.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,2.0,0.000000,0.000,NaN,NaN,0.828021,1.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,1.0,0.601246,0.000,NaN,NaN,0.899950,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356042,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.000000,NaN,NaN,NaN,1.000000,1.0,0.0,1.0,0.0
356043,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.000000,NaN,NaN,NaN,0.986561,1.0,0.0,0.0,0.0
356044,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,2.0,0.299308,0.000,NaN,NaN,0.831397,2.0,0.0,2.0,0.0
356045,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.000000,0.000,NaN,NaN,1.122050,2.0,0.0,1.0,0.0
356046,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,6.0,0.407136,0.000,NaN,NaN,1.115884,6.0,2.0,2.0,0.0

In [3]:
# load pipeline from joblib

loaded_pipe = joblib.load('xgb_pipe.joblib')

# preprocess and predict

preds = loaded_pipe.predict(df)
preds

array([1, 1, 0, ..., 0, 0, 1])